[[BLST]]
arch = "aarch64"
git-tree-sha1 = "c9a77e8ce4ac8aca2ac16def975b88a654c1f5c4"
libc = "glibc"
os = "linux"

    [[BLST.download]]
    sha256 = "b41c3e36e00f7c3918eb3cb22a371f606ddb01938ad29012e7a356e092c023f6"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.3+0/BLST.v0.3.3.aarch64-linux-gnu.tar.gz"
[[BLST]]
arch = "aarch64"
git-tree-sha1 = "15ff48fe564da3a12e7fc752f84b15c352f14606"
libc = "musl"
os = "linux"

    [[BLST.download]]
    sha256 = "ea0882c187c95e0470d61e16acb97c9f2d82122a0aa905281ba97815465a7c3d"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.3+0/BLST.v0.3.3.aarch64-linux-musl.tar.gz"
[[BLST]]
arch = "x86_64"
git-tree-sha1 = "d93a855be6a72a774d5f38f2ccf544e130c02b31"
os = "macos"

    [[BLST.download]]
    sha256 = "0bebe85a00793751d59896b1cae56ce647e302e03186198d5be8b21a63cc8459"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.3+0/BLST.v0.3.3.x86_64-apple-darwin.tar.gz"
[[BLST]]
arch = "x86_64"
git-tree-sha1 = "76b1a75961cb4d32a29af5292bb6d379a6ddc775"
libc = "glibc"
os = "linux"

    [[BLST.download]]
    sha256 = "9f72b943dbb42b289a75bda248eb150dc21f2970687cf744b2b189a1d5e427f7"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.3+0/BLST.v0.3.3.x86_64-linux-gnu.tar.gz"
[[BLST]]
arch = "x86_64"
git-tree-sha1 = "bd4f51693c54d31b69d35f8f6b5c0e27045ca6e7"
libc = "musl"
os = "linux"

    [[BLST.download]]
    sha256 = "e53e8a3558202e447ade8aefc732de8bce8c50f2b25ae3552d2d42d93585c9b3"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.3+0/BLST.v0.3.3.x86_64-linux-musl.tar.gz"
[[BLST]]
arch = "x86_64"
git-tree-sha1 = "f0673e59fdf0d0574bf5adc556eaa760b40418f8"
os = "windows"

    [[BLST.download]]
    sha256 = "5ee89bd2c77426cc5ff8fcd520c135e0a2d15c4c14a05bac5be4d92a8e0526d4"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.3+0/BLST.v0.3.3.x86_64-w64-mingw32.tar.gz"
