[[BLST]]
arch = "aarch64"
git-tree-sha1 = "b10667d3be3a67b8615f60295687169233a9c389"
libc = "glibc"
os = "linux"

    [[BLST.download]]
    sha256 = "6fe87f7829b5fce56c75956fb53f14a7fad61c53aff1d52ed453e7a62caae57b"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.2+0/BLST.v0.3.2.aarch64-linux-gnu.tar.gz"
[[BLST]]
arch = "aarch64"
git-tree-sha1 = "f42a44030750f4d5b79ea4ac34edaec1c0fa7982"
libc = "musl"
os = "linux"

    [[BLST.download]]
    sha256 = "854439a63bf379a0bc0bfb62b9fc0966c76ce74019bc72f7aa54e54e10c675e4"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.2+0/BLST.v0.3.2.aarch64-linux-musl.tar.gz"
[[BLST]]
arch = "x86_64"
git-tree-sha1 = "7f777b89627411eae77aacaf36ef40e0d9a32bf6"
os = "macos"

    [[BLST.download]]
    sha256 = "c7e29cfcc5a10375a05ab5989bc9d7084e2714b2ff528af07b2f289bfc74743f"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.2+0/BLST.v0.3.2.x86_64-apple-darwin.tar.gz"
[[BLST]]
arch = "x86_64"
git-tree-sha1 = "e4c4395fd027ab3f4fdb320d83a87bffbc61bd93"
libc = "glibc"
os = "linux"

    [[BLST.download]]
    sha256 = "06f95144bce839310d9f27aedf3d38c6fa3026a2fb3506443a670b8d97badcd9"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.2+0/BLST.v0.3.2.x86_64-linux-gnu.tar.gz"
[[BLST]]
arch = "x86_64"
git-tree-sha1 = "e42e88a08071cf04c6c0179da0c8c653ce5e2031"
libc = "musl"
os = "linux"

    [[BLST.download]]
    sha256 = "96a27181658f69e7ccbb908685cfc1cdd69e36a3ecda82cff1144606aba505f1"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.2+0/BLST.v0.3.2.x86_64-linux-musl.tar.gz"
[[BLST]]
arch = "x86_64"
git-tree-sha1 = "980a9669fd2784c7d366957d757fc8c2608987b9"
os = "windows"

    [[BLST.download]]
    sha256 = "17abd6936620b4197a35caccfc316685748b2077e7921944795fb0a9c805c43c"
    url = "https://github.com/JuliaBinaryWrappers/BLST_jll.jl/releases/download/BLST-v0.3.2+0/BLST.v0.3.2.x86_64-w64-mingw32.tar.gz"
