# Autogenerated wrapper script for BLST_jll for x86_64-w64-mingw32
export libblst

JLLWrappers.@generate_wrapper_header("BLST")
JLLWrappers.@declare_library_product(libblst, "libblst.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libblst,
        "bin\\libblst.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
