# Autogenerated wrapper script for BLST_jll for x86_64-apple-darwin
export libblst

JLLWrappers.@generate_wrapper_header("BLST")
JLLWrappers.@declare_library_product(libblst, "@rpath/libblst.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libblst,
        "lib/libblst.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
